/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/+__root'
import { Route as ViewerImport } from './routes/+viewer_'
import { Route as GmImport } from './routes/+_gm'
import { Route as GmIndexImport } from './routes/+_gm/+index'
import { Route as GmTimelineIndexImport } from './routes/+_gm/+timeline/+index'

// Create/Update Routes

const ViewerRoute = ViewerImport.update({
  path: '/viewer',
  getParentRoute: () => rootRoute,
} as any)

const GmRoute = GmImport.update({
  id: '/_gm',
  getParentRoute: () => rootRoute,
} as any)

const GmIndexRoute = GmIndexImport.update({
  path: '/',
  getParentRoute: () => GmRoute,
} as any)

const GmTimelineIndexRoute = GmTimelineIndexImport.update({
  path: '/timeline/',
  getParentRoute: () => GmRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_gm': {
      id: '/_gm'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GmImport
      parentRoute: typeof rootRoute
    }
    '/viewer': {
      id: '/viewer'
      path: '/viewer'
      fullPath: '/viewer'
      preLoaderRoute: typeof ViewerImport
      parentRoute: typeof rootRoute
    }
    '/_gm/': {
      id: '/_gm/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GmIndexImport
      parentRoute: typeof GmImport
    }
    '/_gm/timeline/': {
      id: '/_gm/timeline/'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof GmTimelineIndexImport
      parentRoute: typeof GmImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  GmRoute: GmRoute.addChildren({ GmIndexRoute, GmTimelineIndexRoute }),
  ViewerRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "+__root.tsx",
      "children": [
        "/_gm",
        "/viewer"
      ]
    },
    "/_gm": {
      "filePath": "+_gm.tsx",
      "children": [
        "/_gm/",
        "/_gm/timeline/"
      ]
    },
    "/viewer": {
      "filePath": "+viewer_.tsx"
    },
    "/_gm/": {
      "filePath": "+_gm/+index.tsx",
      "parent": "/_gm"
    },
    "/_gm/timeline/": {
      "filePath": "+_gm/+timeline/+index.tsx",
      "parent": "/_gm"
    }
  }
}
ROUTE_MANIFEST_END */
